Feature/voight kampff
MycroftAI/mycroft-skills pull request #1288
Opened 2020-03-27 00:28 UTC by chrisveilleux

## Description:

This is not a new or updated skill.  It is s an introduction of integration tests into the skill repository.

2020-03-28 20:58 UTC, forslund requested changes
Mostly looks good, the big question I have is how default skills are updated to the latest version and tested alongside the new skill.

There's some minor things like the api-key should be used instead of user/password and some unnecessary underscores.

Interesting approach with using requests for fetching the diff instead of using git :+1:

2020-03-28 20:58 UTC, forslund commented on build_test_config.py
> +        config_file.write('- ' + skill_submodule_name + '\n')
Will this method also enforce that all the default skills are tested? or will that be picked up from the base image? In that case a `msm update` step may be required.

2020-03-28 20:58 UTC, forslund commented on build_test_config.py
> +    g = Github(environ['GITHUB_USER'], environ['GITHUB_PASSWORD'])
User/Pass is deprecated, should use an API key (pretty straight forward, but if you want to look at something it's used in mycroft-skills-kit)

2020-03-28 20:58 UTC, forslund commented on build_test_config.py
> +    write_test_config_file(_skill_submodule_name)
The leading `_` aren't really useful and just makes this harder to read since this is not anything that will be exported.

2020-03-28 20:58 UTC, forslund commented on build_test_config.py
> +        config_file.write('- ' + skill_submodule_name + '\n')
Also should pyyaml be considered instead of writing the yaml manually? Not a big deal though if it's going to stay this simple.

2020-03-30 17:54 UTC, chrisveilleux commented on build_test_config.py
> +        config_file.write('- ' + skill_submodule_name + '\n')
The base docker image contains all the default skills. I thought skills updated automatically upon startup.

2020-03-30 17:55 UTC, chrisveilleux commented on build_test_config.py
> +        config_file.write('- ' + skill_submodule_name + '\n')
I could use pyyaml, but will probably just leave it as is for now since it is two lines

2020-03-30 17:59 UTC, chrisveilleux commented on build_test_config.py
> +    write_test_config_file(_skill_submodule_name)
They are useful.  If I remove the leading underscore, they have the same name as the arguments defined in the functions, which presents a possible scoping issue.  When I change _args to args, my editor immediately complains that the function parameter is shadowing a name from the outer scope

2020-03-30 18:20 UTC, forslund commented on build_test_config.py
> +    write_test_config_file(_skill_submodule_name)
Fair point, then I suggest you instead use a `main()` function. Simple, nice variable names and protected scope.

2020-03-30 18:22 UTC, forslund commented on build_test_config.py
> +        config_file.write('- ' + skill_submodule_name + '\n')
The default skills will be updated but the initial tests will execute with the old skills until they are installed. (First we load all skills and get to a usable state, then we check for updates).

2020-03-30 19:41 UTC, chrisveilleux commented on build_test_config.py
> +        config_file.write('- ' + skill_submodule_name + '\n')
added a `msm update` step to the Dockerfile

2020-03-31 15:16 UTC, forslund commented
Looks good. You can probably remove the `.travis.yml` since it's failing with these changes (uses old python version and can't get the latest pygithub). The only thing that script checked was that the submodules could be fetched and I think jenkins could be repurposed to do that.

2020-03-31 15:16 UTC, forslund approved these changes

2020-04-01 19:00 UTC, merged